### PR TITLE
Cache: Make cache public

### PR DESCRIPTION
**Pull request by gamab**
Fix: https://github.com/grafana/authlib/issues/19

### CODE REVIEW

**Review by kalleep — COMMENTED** [review]
Btw we should probably change from go-cache to something like https://github.com/dgraph-io/ristretto. Then we can control the size of the cache

**Comment by gamab** [comment]
> Well right now we are not exposing a way to configure the cache even with this pr right? If you want that ability then I think authz should expose its own cache interface and expose wrapped errors?

Yes we are:
```go
func WithCache(cache cache.Cache) ClientOption
```

But we can come back on that decision and provide:
```
func WithCacheOption(cache cache.CacheOption) ClientOption
```

**Comment by kalleep** [comment]
oh yeah you are right, that is strange. We are exposing a function with an interface from an internal package..

Any way do we have a case for custom implementation of the cache? Otherwise we should not expose it and just cache options I guess and when/if we have a use case for custom cache we add support for it. No need to add stuff we don't need

**Comment by Jguer** [comment]
My opinion on this is that right now it's useful for us to expose it and it's getting in the way of development. Let's optimize for now here and not for when this lib is used by a 1000 integrations.

**Review by Jguer — APPROVED** [review]

**Comment by gamab** [comment]
Ok, let's merge this then, at least the cache would be override-able.

**Pull request merged**
